### ISSUE TITLE
Load adapter fusion error

### ISSUE THREAD

**Issue by FunnyJingl** [johndmendonca/qualityadapt#1]
Hey,
while loading code for overall quality after downloading model:

```Python 
# Overall Quality prediction
model.load_adapter("QualityAdapt/exp/"+model_str+"/Understandability",load_as="U", with_head=False)
model.load_adapter("QualityAdapt/exp/"+model_str+"/Sensibleness",load_as="S", with_head=False)
model.load_adapter_fusion("QualityAdapt/exp/"+model_str+"/Human/U,S")   #  <--- error
model.load_head("QualityAdapt/exp/"+model_str+"/Human/Human")
```

got error:
`ValueError: Loading path should be a directory where AdapterFusion is saved.`

Please, explain how this path should looks.

**Comment by johndmendonca** [comment]
Hi,

The original drive .zip file did not contain `/U,S`. I updated the drive to now include this.
